name: Release OSS (APK)

on:
  push:
    tags:
      - v*

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Sign App
        id: sign_app
        run: echo "signedFiles=/home/runner/work/GitSync/GitSync/build/app/outputs/flutter-apk/app-arm64-v8a-release-signed.apk:/home/runner/work/GitSync/GitSync/build/app/outputs/flutter-apk/app-armeabi-v7a-release-signed.apk:/home/runner/work/GitSync/GitSync/build/app/outputs/flutter-apk/app-x86_64-release-signed.apk" >> "$GITHUB_OUTPUT"

      - uses: jungwinter/split@v2
        id: signed_files
        with:
          msg: ${{ steps.sign_app.outputs.signedFiles }}
          separator: ":"

      - name: Manual Split
        id: signed_files2
        run: IFS=':' read -ra arr <<< "${{ steps.sign_app.outputs.signedFiles }}"; for i in "${!arr[@]}"; do echo "_$i=${arr[$i]}" >> GITHUB_OUTPUT; done
